### ISSUE TITLE
KNOWN ISSUE: Facing east while trophy fishing causes pitch to freeze at 0.

### ISSUE THREAD

**Issue by StarZebra** [StarZebra/Nexus#1]
title and im working on it.

**Comment by AtroxEGO** [comment]
Need any help resolving it?

**Comment by StarZebra** [comment]
> AtroxEGO

Sure that would be fine I am currently a bit busy and not working on this atm.

**Comment by StarZebra** [comment]
commit #aa675bc fixes this
